FORMAT: 1A

# Minerva

## Info [/api]

### Fetch info [GET /api]
+ Response 200 (application/json; charset=utf-8)
    + Attributes (Info)

## Info [/api]

### Fetch info [GET /list]
+ Response 200 (application/json; charset=utf-8)
    + Attributes (array[number])

# Data Structures

## Info (object)
    - started: `2017-01-20T15:56:26.817Z` (string)
