language: node_js
cache:
  directories:
    - node_modules
node_js:
  - 6.11.3
before_install:
  - npm install -g npm
before_script:
  - npm run link
after_success:
  - npm start build && npm start docs
